### ISSUE TITLE
GAM Freezes on installation on Ubuntu WSL2 running on Windows 10

### ISSUE THREAD

**Issue by dweisinger21** [GAM-team/GAM#1516] opened 2022-04-21 15:37 UTC
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. Run bash install command
2. Select running through SSH or with GUI, neither work
3. URL is given, but no input is accepted when the prompt appears stating "Enter verification code or browser URL:"

Expected outcome (what are you trying to do?):
I should be able to paste the URL into the terminal, but the terminal becomes unresponsive. This occurs both over SSH via Putty and in the WSL2 console.

Actual outcome (what errors or bad behavior do you see instead?):
Completely frozen, must close out and reopen.

**Comment by jay0lee** [comment] 2022-05-21 13:32
WSL is not being tested today and this I cannot guarantee it works.

My recommendation would be to either run the Windows version or setup a full Linux server (not WSL) to run GAM.

**Comment by ticoombs** [comment] 2022-10-05 01:41
I've been using GAM on WSL for over 5 years. I've confirmed that the recent changes make deployment impossible and freezes.
I've gone through and confirmed that this is a recent change and:

Works in version: <= 6.15 (and below)
Doesnt work: > 6.15

The first version that introduced this error was (of course) v6.16 
----
This happens due to from 6.16 starts a browser. Before 6.16 it never attempted to start a browser
![image](https://user-images.githubusercontent.com/2687896/193960524-32c6ae9d-9364-4b73-8573-c5c02ace611f.png)

This happens regardless if `nobrowser.txt` exists or doesnt exist. It seems we no longer have that functionality.

**Comment by jay0lee** [comment] 2022-11-01 20:59
This should be fixed in GAM 6.30 released today.

**Closed by jay0lee** 2022-11-01 20:59 UTC
Labels: bug

**Comment by ticoombs** [comment] 2022-11-01 23:32
Confirming latest version fixes the issue related to oauth flow (when `nobrowser.txt` is present).

Thankyou!
