### ISSUE TITLE
get drivefile query - don't support cyrillic filenames

### ISSUE THREAD

**Issue by sksurpriseme** [GAM-team/GAM#1216] opened 2020-06-24 08:25 UTC
When i download files using command

`gam user $EMAIL get drivefile query "'me' in owners" format microsoft targetfolder $pathtofoldier`

filenames have empty space.

**Comment by jay0lee** [comment] 2020-06-30 13:19
This is working as intended. Google Drive supports a much wider range of filename characters than most operating systems do. In order to successfully download the file GAM has to choose a filename for the file that is valid on the OS GAM is running and this varies widely across Windows, Linux and MacOS. So as a safety precaution, GAM removes any characters from the Google Drive filename that aren't in the English alphabet (26 characters, upper and lower), numbers 0-9 or the exact characters `-_.() `. (note that space character is included there).

Admittedly, while this is working as intended it's not terribly user friendly and I'm sure it completely mutilates some filenames, especially in the non-English-speaking majority of the world. It was a decision made to keep things simple and reliable if far from perfect.

What we could look at doing is pulling in a 3rd party Python library like [pathvalidate](https://github.com/thombashi/pathvalidate) which can handle the challenge of converting a filename from Google Drive's allowed characters to something the local OS/filesystem supports much more gracefully and with far less mangling.

Marking this as an enhancement and help wanted if anyone is interested in switching GAM to using pathvalidate or something similar. The relevant code would be found around:

https://github.com/jay0lee/GAM/blob/master/src/gam/__init__.py#L3860

**Comment by sksurpriseme** [comment] 2020-07-01 13:08
thx a lot for your response. 
i'm are not developer, so i can't do it by my self. Hope, someone will help with it

**Comment by mrPsycho** [comment] 2021-03-18 20:58
yes, this is quite strange, that only english chars are supported.

**Comment by mrPsycho** [comment] 2021-08-05 16:42
finally i managed to check it deeper, and found, that editing `gam/var.py`  with something like that:
`FILENAME_SAFE_CHARS = FILENAME_SAFE_CHARS + 'АБВГДЕЁЖЗИКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзиклмнопрстуфхцчшщьыъэюя'` 
solves issue locally. 

now need to understand how to use `pathvalidate`

**Comment by mrPsycho** [comment] 2021-08-05 17:25
looks like it was easier, than i thought. @jay0lee  please check #1408

**Comment by jay0lee** [comment] 2024-10-03 10:57
closing this as PR was committed long ago...

**Closed by jay0lee** 2024-10-03 10:57 UTC
Labels: enhancement, help wanted
